Study/Controllers/FacilitiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Study.Extensions;
using Study.Services;
using Univercity.Application.ViewModels;
using Univercity.Domain;
using Univercity.Persistence;

namespace Study.Controllers
{
    public class FacilitiesController : Controller
    {
        private readonly LessonsDbContext _context;
        private readonly int pageSize = 12;

        public FacilitiesController(LessonsDbContext context)
        {
            _context = context;
        }

        // GET: Facilities
        // GET: facilityTypes
        public async Task<IActionResult> Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();
            FacilitiesViewModel facilitys;
            var facility = HttpContext.Session.Get<FacilitiesViewModel>("Facility");
            if (facility == null)
            {
                facility = new FacilitiesViewModel();
            }
            IEnumerable<Facility> facilityDbContext = cache.GetFacilities();
            facilityDbContext = Sort_Search(facilityDbContext, sortOrder, facility.FacilityName ?? "");
            // Разбиение на страницы
            var count = facilityDbContext.Count();
            facilityDbContext = facilityDbContext.Skip((page - 1) * pageSize).Take(pageSize);

            facilitys = new FacilitiesViewModel
            {
                Facilities = facilityDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortOrder),
                FacilityName = facility.FacilityName
            };

            return View(facilitys);
        }
        [HttpPost]
        public IActionResult Index(FacilitiesViewModel facility)
        {

            HttpContext.Session.Set("Facility", facility);

            return RedirectToAction("Index");
        }

        // GET: Facilities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();

            if (id == null || _context.Facilities == null)
            {
                return NotFound();
            }

            var facility = cache.GetFacilities()
                .FirstOrDefault(m => m.FacilityId == id);
            if (facility == null)
            {
                return NotFound();
            }

            return View(facility);
        }

        // GET: Facilities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Facilities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FacilityId,FacilityName")] Facility facility)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();

            if (ModelState.IsValid)
            {
                _context.Add(facility);
                await _context.SaveChangesAsync();
                cache.SetFacilities();
                return RedirectToAction(nameof(Index));
            }
            return View(facility);
        }

        // GET: Facilities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();

            if (id == null || _context.Facilities == null)
            {
                return NotFound();
            }

            var facility = cache.GetFacilities()
                .FirstOrDefault(m => m.FacilityId == id);
            if (facility == null)
            {
                return NotFound();
            }
            return View(facility);
        }

        // POST: Facilities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FacilityId,FacilityName")] Facility facility)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();
            var cacheSG = HttpContext.RequestServices.GetService<StudentsGroupService>();
            var cacheL = HttpContext.RequestServices.GetService<LessonService>();
            if (id != facility.FacilityId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facility);
                    await _context.SaveChangesAsync();
                    cache.SetFacilities();
                    cacheSG.SetStudentsGroups();
                    cacheL.SetLessons();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacilityExists(facility.FacilityId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(facility);
        }

        // GET: Facilities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();

            if (id == null || _context.Facilities == null)
            {
                return NotFound();
            }

            var facility = cache.GetFacilities()
                .FirstOrDefault(m => m.FacilityId == id);
            if (facility == null)
            {
                return NotFound();
            }

            return View(facility);
        }

        // POST: Facilities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetService<FacilityService>();
            var cacheSG = HttpContext.RequestServices.GetService<StudentsGroupService>();
            var cacheL = HttpContext.RequestServices.GetService<LessonService>();
            if (_context.Facilities == null)
            {
                return Problem("Entity set 'LessonsDbContext.Facilities'  is null.");
            }
            var facility = cache.GetFacilities()
.FirstOrDefault(m => m.FacilityId == id);
            var studentGroups =   cacheSG.GetStudentsGroups().Where(c => c.FacilityId == id);
            if (facility != null)
            {
                foreach (var studentGroup in studentGroups)
                {
                    _context.Lessons.RemoveRange(studentGroup.Lessons);
                }
                _context.SaveChanges();
                cache.SetFacilities();
                cacheSG.SetStudentsGroups();
                facility = cache.GetFacilities()
.FirstOrDefault(m => m.FacilityId == id);
                _context.StudentsGroups.RemoveRange(facility.StudentsGroups);
                cache.SetFacilities();
                cacheSG.SetStudentsGroups();
                await _context.SaveChangesAsync();

                _context.Facilities.Remove(facility);
               


            }

            await _context.SaveChangesAsync();
            cache.SetFacilities();
            cacheSG.SetStudentsGroups();
            cacheL.SetLessons();
            return RedirectToAction(nameof(Index));
        }

        private bool FacilityExists(int id)
        {
          return (_context.Facilities?.Any(e => e.FacilityId == id)).GetValueOrDefault();
        }
        private IEnumerable<Facility> Sort_Search(IEnumerable<Facility> facilities, SortState sortOrder, string searchFacility)
        {
            switch (sortOrder)
            {
                case SortState.FacilityNameAsc: 
                    facilities = facilities.OrderBy(s => s.FacilityName);
                    break;
                case SortState.FacilityNameDesc:
                    facilities = facilities.OrderByDescending(s => s.FacilityName);
                    break;
            }
            facilities = facilities.Where(o => o.FacilityName.Contains(searchFacility ?? ""));

            return facilities;
        }
    }
}

Study/Views/Facilities/Create.cshtml
@model Facility

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить</h1>

<h4>Факультет</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FacilityName" class="control-label"></label>
                <input asp-for="FacilityName" class="form-control" />
                <span asp-validation-for="FacilityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/Facilities/Delete.cshtml
@model Facility

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удалить</h1>

<h3>Вы уроверены что хотите этого</h3>
<div>
    <h4>Facility</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacilityName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FacilityId" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Study/Views/Facilities/Details.cshtml
@model Facility

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Детали</h1>

<div>
    <h4>Факультет</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacilityName)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("admin")){
        <a class="link-warning"  asp-action="Edit" asp-route-id="@Model?.FacilityId">Обновить</a>
    }
    <a asp-action="Index">Вернутся к списку</a>
</div>

Study/Views/Facilities/Edit.cshtml
@model Facility

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Обновить</h1>

<h4>Факультет</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FacilityId" />
            <div class="form-group">
                <label asp-for="FacilityName" class="control-label"></label>
                <input asp-for="FacilityName" class="form-control" />
                <span asp-validation-for="FacilityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-outline-warning" type="submit" value="Save"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/Facilities/Index.cshtml
@model FacilitiesViewModel

@{
    ViewData["Title"] = "Факультеты";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string FacilityName = Model.FacilityName;
}

<h1>Факультеты</h1>

@if (User.IsInRole("admin"))
{
    <p>
        <a class="link-success" asp-action="Create">Добавить</a>
    </p>
}
<form action="@Url.Action("Index", "Facilities")" method="post">
    <div class="row g-3">
        <div class="col-auto">
            @Html.TextBox("FacilityName", FacilityName, new {placeholder="Тип дисциплины", style = "width: 100px;",@class="form-control custom-font-size"})
        </div>
        <div class="col-auto">
            <input class="btn btn-outline-primary" style="margin-left: 10px" type="submit" value="Найти" />
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.SortViewModel.FacilityNameState>
                    @Html.DisplayNameFor(model => model.FacilityName)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Facilities) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityName)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    <a class="link-warning" asp-action="Edit" asp-route-id="@item.FacilityId">Обновить</a> |
                    <a class="link-info" asp-action="Details" asp-route-id="@item.FacilityId">Детали</a> |
                    <a class="link-danger" asp-action="Delete" asp-route-id="@item.FacilityId">Удалить</a>
                </td>
            }
            else
            {
                <td>
                    <a class="link-info" asp-action="Details" asp-route-id="@item.FacilityId">Детали</a> |
                </td>
            }
        </tr>
}
    </tbody>
</table>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>