Study/Controllers/DisciplinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Study.Extensions;
using Study.Services;
using Univercity.Application.ViewModels;
using Univercity.Domain;
using Univercity.Persistence;

namespace Study.Controllers
{
    public class DisciplinesController : Controller
    {
        private readonly LessonsDbContext _context;
        private readonly int pageSize = 12;

        public DisciplinesController(LessonsDbContext context)
        {
            _context = context;
        }

        // GET: DisciplineTypes
        public async Task<IActionResult> Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            DisciplinesViewModel disciplines;
            var discipline = HttpContext.Session.Get<DisciplinesViewModel>("Discipline");
            if (discipline == null)
            {
                discipline = new DisciplinesViewModel();
            }
            IEnumerable<Discipline> disciplineDbContext = cache.GetDisciplines();
            disciplineDbContext = Sort_Search(disciplineDbContext, sortOrder, discipline.DisciplineName ?? "");
            // Разбиение на страницы
            var count = disciplineDbContext.Count();
            disciplineDbContext = disciplineDbContext.Skip((page - 1) * pageSize).Take(pageSize);

            disciplines = new DisciplinesViewModel
            {
                Disciplines = disciplineDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortOrder),
                DisciplineName = discipline.DisciplineName
            };

            return View(disciplines);
        }
        [HttpPost]
        public IActionResult Index(DisciplinesViewModel discipline)
        {

            HttpContext.Session.Set("Discipline", discipline);

            return RedirectToAction("Index");
        }
        // GET: Disciplines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (id == null || _context.Disciplines == null)
            {
                return NotFound();
            }

            var discipline = cache.GetDisciplines()
                .FirstOrDefault(m => m.DisciplineId == id);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // GET: Disciplines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Disciplines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DisciplineId,DisciplineName")] Discipline discipline)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (ModelState.IsValid)
            {
                _context.Add(discipline);
                await _context.SaveChangesAsync();
                cache.SetDisciplines();

                return RedirectToAction(nameof(Index));
            }
            return View(discipline);
        }

        // GET: Disciplines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (id == null || _context.Disciplines == null)
            {
                return NotFound();
            }

            var discipline = cache.GetDisciplines()
                .FirstOrDefault(m => m.DisciplineId == id);
            if (discipline == null)
            {
                return NotFound();
            }
            return View(discipline);
        }

        // POST: Disciplines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DisciplineId,DisciplineName")] Discipline discipline)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (id != discipline.DisciplineId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(discipline);
                    await _context.SaveChangesAsync();
                    cache.SetDisciplines();
                    var casheL = HttpContext.RequestServices.GetService<LessonService>();
                    casheL.SetLessons();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisciplineExists(discipline.DisciplineId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(discipline);
        }

        // GET: Disciplines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (id == null || _context.Disciplines == null)
            {
                return NotFound();
            }
            var discipline = cache.GetDisciplines()
                .FirstOrDefault(m => m.DisciplineId == id);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // POST: Disciplines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetService<DisciplineService>();

            if (_context.Disciplines == null)
            {
                return Problem("Entity set 'LessonsDbContext.Disciplines'  is null.");
            }
            var discipline = cache.GetDisciplines()
                .FirstOrDefault(m => m.DisciplineId == id); 
            if (discipline != null)
            {
                _context.Disciplines.Remove(discipline);
                _context.Lessons.RemoveRange(discipline.Lessons);
            }
            
            await _context.SaveChangesAsync();
            cache.SetDisciplines();
            var casheL = HttpContext.RequestServices.GetService<LessonService>();
            casheL.SetLessons();
            return RedirectToAction(nameof(Index));
        }

        private bool DisciplineExists(int id)
        {
          return (_context.Disciplines?.Any(e => e.DisciplineId == id)).GetValueOrDefault();
        }
        private IEnumerable<Discipline> Sort_Search(IEnumerable<Discipline> disciplines, SortState sortOrder, string searchDiscipline)
        {
            switch (sortOrder)
            {
                case SortState.DisciplineNameAsc:
                    disciplines = disciplines.OrderBy(s => s.DisciplineName);
                    break;
                case SortState.DisciplineNameDesc:
                    disciplines = disciplines.OrderByDescending(s => s.DisciplineName);
                    break;
            }
            disciplines = disciplines.Where(o => o.DisciplineName.Contains(searchDiscipline ?? ""));

            return disciplines;
        }
    }
}

Study/Views/Disciplines/Create.cshtml
@model Discipline

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить</h1>

<h4>Дисциплина</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DisciplineName" class="control-label"></label>
                <input asp-for="DisciplineName" class="form-control" />
                <span asp-validation-for="DisciplineName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/Disciplines/Delete.cshtml
@model Discipline

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удалить</h1>

<h3>Вы уроверены что хотите этого</h3>
<div>
    <h4>Discipline</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisciplineName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisciplineName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DisciplineId" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Study/Views/Disciplines/Details.cshtml
@model Discipline

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Детали</h1>

<div>
    <h4>Дисциплина</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisciplineName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisciplineName)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("admin")){
        <a class="link-warning" asp-action="Edit" asp-route-id="@Model?.DisciplineId">Обновить</a>
    }
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/Disciplines/Edit.cshtml
@model Discipline

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Обновить</h1>

<h4>Дисциплина</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DisciplineId" />
            <div class="form-group">
                <label asp-for="DisciplineName" class="control-label"></label>
                <input asp-for="DisciplineName" class="form-control" />
                <span asp-validation-for="DisciplineName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-outline-warning" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/Disciplines/Index.cshtml
@model DisciplinesViewModel

@{
    ViewData["Title"] = "Дисциплины";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string DisciplineName = Model.DisciplineName;
}

<h1>Дисциплины</h1>

@if (User.IsInRole("admin"))
{
    <p>
        <a class ="link-success" asp-action="Create">Добавить</a>
    </p>
}
<form action="@Url.Action("Index", "Disciplines")" method="post">
    <div class="row g-3">
        <div class="col-auto">
            @Html.TextBox("DisciplineName", DisciplineName, new {placeholder="Дисциплина", style = "width: 100px;",@class="form-control custom-font-size"})
        </div>
        <div class="col-auto">
            <input class="btn btn-outline-primary" style="margin-left: 10px" type="submit" value="Найти" />
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.SortViewModel.DisciplineNameSort>
                    @Html.DisplayNameFor(model => model.DisciplineName)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Disciplines) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DisciplineName)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    <a class="link-warning" asp-action="Edit" asp-route-id="@item.DisciplineId">Обновить</a> |
                    <a class="link-info" asp-action="Details" asp-route-id="@item.DisciplineId">Детали</a> |
                    <a class="link-danger" asp-action="Delete" asp-route-id="@item.DisciplineId">Удалить</a>
                </td>
            }
            else
            {
                <td>
                    <a class="link-info" asp-action="Details" asp-route-id="@item.DisciplineId">Детали</a> |
                </td>
            }
        </tr>
}
    </tbody>
</table>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>