Study/Controllers/LessonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Study.Extensions;
using Univercity.Application.ViewModels;
using Univercity.Domain;
using Study.Services;
using Univercity.Persistence;

namespace Study.Controllers
{
    public class LessonsController : Controller
    {
        private readonly LessonsDbContext _context;
        private readonly int pageSize = 8;  // количество элементов на странице
        public LessonsController(LessonsDbContext context)
        {
            _context = context;

        }
        // GET: Lessons
        [ResponseCache(CacheProfileName = "ModelCache")]
        //[SetToSession("Less")]
        public IActionResult Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            LessonsViewModel lessons;
            var lesson = HttpContext.Session.Get<FilterLessonViewModel>("Lesson");
            if (lesson == null)
            {
                lesson = new FilterLessonViewModel();
            }
            IEnumerable<Lesson> lessonsDbContext = cache.GetLessons();
            lessonsDbContext = Sort_Search(lessonsDbContext, sortOrder, lesson.Discipline ?? "", lesson.Teacher ?? "", lesson.LessonTime, lesson.Facility ?? "", lesson.Classroom,
                lesson.StudentGroup ?? "", lesson.DisciplineType ?? "", lesson.Year, lesson.DayOfweek, lesson.Semestr, lesson.LessonDate);
            // Разбиение на страницы

            var count = lessonsDbContext.Count();
            lessonsDbContext = lessonsDbContext.Skip((page - 1) * pageSize).Take(pageSize);

            lessons = new LessonsViewModel
            {
                Lessons = lessonsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortOrder),
                FilterLessonViewModel = lesson
            };
            return View(lessons);
        }
        [HttpPost]
        public IActionResult Index(FilterLessonViewModel lesson)
        {

            HttpContext.Session.Set("Lesson", lesson);

            return RedirectToAction("Index");
        }


        // GET: Lessons/Details/5
        public IActionResult Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();
            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = _context.Lessons.Include(l => l.Classroom).Include(l => l.Discipline).Include(l => l.DisciplineType).Include(l => l.LessonTime).Include(l => l.StudentsGroup).Include(l => l.Teacher)
                .FirstOrDefault(m => m.LessonId == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // GET: Lessons/Create
        public IActionResult Create()
        {
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "ClassroomId", "NumberOfClassroom");
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "DisciplineId", "DisciplineName");
            ViewData["DisciplineTypeId"] = new SelectList(_context.DisciplineTypes, "DisciplineTypeId", "TypeOfDiscipline");
            ViewData["LessonTimeId"] = new SelectList(_context.LessonsTimes, "LessonTimeId", "LessonTime");
            ViewData["StudentsGroupId"] = new SelectList(_context.StudentsGroups, "StudentsGroupId", "NumberOfGroup");
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "TeacherId", "TeacherName");
            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LessonId,DisciplineId,ClassroomId,DisciplineTypeId,TeacherId,StudentsGroupId,Semestr,LessonDate,LessonTimeId,Year,DayOfweek")] Lesson lesson)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            if (ModelState.IsValid)
            {
                lesson.Year = lesson.LessonDate.Value.Year;
                lesson.DayOfweek = ((int)lesson.LessonDate.Value.DayOfWeek + 6) % 7 + 1;
                _context.Add(lesson);
                await _context.SaveChangesAsync();
                cache.SetLessons();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "ClassroomId", "NumberOfClassroom", lesson.ClassroomId);
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "DisciplineId", "DisciplineName", lesson.DisciplineId);
            ViewData["DisciplineTypeId"] = new SelectList(_context.DisciplineTypes, "DisciplineTypeId", "TypeOfDiscipline", lesson.DisciplineTypeId);
            ViewData["LessonTimeId"] = new SelectList(_context.LessonsTimes, "LessonTimeId", "LessonTime", lesson.LessonTimeId);
            ViewData["StudentsGroupId"] = new SelectList(_context.StudentsGroups, "StudentsGroupId", "NumberOfGroup", lesson.StudentsGroupId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "TeacherId", "TeacherName", lesson.TeacherId);
            return View(lesson);
        }

        // GET: Lessons/Edit/5
        public IActionResult Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = cache.GetLessons().FirstOrDefault(m => m.LessonId == id);
            if (lesson == null)
            {
                return NotFound();
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "ClassroomId", "NumberOfClassroom", lesson.ClassroomId);
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "DisciplineId", "DisciplineName", lesson.DisciplineId);
            ViewData["DisciplineTypeId"] = new SelectList(_context.DisciplineTypes, "DisciplineTypeId", "TypeOfDiscipline", lesson.DisciplineTypeId);
            ViewData["LessonTimeId"] = new SelectList(_context.LessonsTimes, "LessonTimeId", "LessonTime", lesson.LessonTimeId);
            ViewData["StudentsGroupId"] = new SelectList(_context.StudentsGroups, "StudentsGroupId", "NumberOfGroup", lesson.StudentsGroupId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "TeacherId", "TeacherName", lesson.TeacherId);
            return View(lesson);
        }

        // POST: Lessons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LessonId,DisciplineId,ClassroomId,DisciplineTypeId,TeacherId,StudentsGroupId,Semestr,LessonDate,LessonTimeId,Year,DayOfweek")] Lesson lesson)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            if (id != lesson.LessonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    lesson.Year = lesson.LessonDate.Value.Year;
                    lesson.DayOfweek = ((int)lesson.LessonDate.Value.DayOfWeek + 6) % 7 + 1;
                    _context.Update(lesson);
                    await _context.SaveChangesAsync();
                    cache.SetLessons();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LessonExists(lesson.LessonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "ClassroomId", "NumberOfClassroom", lesson.ClassroomId);
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "DisciplineId", "DisciplineName", lesson.DisciplineId);
            ViewData["DisciplineTypeId"] = new SelectList(_context.DisciplineTypes, "DisciplineTypeId", "TypeOfDiscipline", lesson.DisciplineTypeId);
            ViewData["LessonTimeId"] = new SelectList(_context.LessonsTimes, "LessonTimeId", "LessonTime", lesson.LessonTimeId);
            ViewData["StudentsGroupId"] = new SelectList(_context.StudentsGroups, "StudentsGroupId", "NumberOfGroup", lesson.StudentsGroupId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "TeacherId", "TeacherName", lesson.TeacherId);
            return View(lesson);
        }

        // GET: Lessons/Delete/5
        public IActionResult Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = cache.GetLessons().FirstOrDefault(l => l.LessonId == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetService<LessonService>();

            if (_context.Lessons == null)
            {

Study/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Univercity.Application.ViewModels;

namespace Study.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Study/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Study</title>
    <link rel="stylesheet" href="~/css/boot.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Study.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="font-size: 18px" asp-area="" asp-controller="Home" asp-action="Index">Университет</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Lessons" asp-action="Index">Уроки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentsGroups" asp-action="Index">Группы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Classrooms" asp-action="Index">Аудитории</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Facilities" asp-action="Index">Факультеты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LessonsTimes" asp-action="Index">Время начала</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DisciplineTypes" asp-action="Index">Типы дисциплин</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Disciplines" asp-action="Index">Дисциплины</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Учителя</a>
                            </li>
                            if(User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container " >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Study - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>