Study/Controllers/StudentsGroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Study.Extensions;
using Univercity.Application.ViewModels;
using Univercity.Domain;
using Univercity.Persistence;
using Study.Services;

namespace Study.Controllers
{
    public class StudentsGroupsController : Controller
    {
        private readonly LessonsDbContext _context;
        private readonly int pageSize = 12;

        public StudentsGroupsController(LessonsDbContext context)
        {
            _context = context;
        }

        // GET: StudentsGroups
        [ResponseCache(CacheProfileName = "ModelCache")]
        // GET: facilityTypes
        public async Task<IActionResult> Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();
            StudentsGroupViewModel studentsGroups;
            var studentsGroup = HttpContext.Session.Get<StudentsGroupViewModel>("StudentGroup");
            if (studentsGroup == null)
            {
                studentsGroup = new StudentsGroupViewModel();
            }
            IEnumerable<StudentsGroup> studentGroupDbContext = cache.GetStudentsGroups();
            studentGroupDbContext = Sort_Search(studentGroupDbContext, sortOrder, studentsGroup.Facility ?? "", studentsGroup.NumberOfGroup ?? "");
            // Разбиение на страницы
            var count = studentGroupDbContext.Count();
            studentGroupDbContext = studentGroupDbContext.Skip((page - 1) * pageSize).Take(pageSize);

            studentsGroups = new StudentsGroupViewModel
            {
                StudentsGroups = studentGroupDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortOrder),
                NumberOfGroup = studentsGroup.NumberOfGroup,
                Facility = studentsGroup.Facility
            };

            return View(studentsGroups);
        }
        [HttpPost]
        public IActionResult Index(StudentsGroupViewModel studentGroup)
        {

            HttpContext.Session.Set("StudentGroup", studentGroup);

            return RedirectToAction("Index");
        }

        // GET: StudentsGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (id == null || _context.StudentsGroups == null)
            {
                return NotFound();
            }

            var studentsGroup = cache.GetStudentsGroups()
                .FirstOrDefault(m => m.StudentsGroupId == id);
            if (studentsGroup == null)
            {
                return NotFound();
            }

            return View(studentsGroup);
        }

        // GET: StudentsGroups/Create
        public IActionResult Create()
        {
            ViewData["FacilityId"] = new SelectList(_context.Facilities, "FacilityId", "FacilityName");
            return View();
        }

        // POST: StudentsGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentsGroupId,NumberOfGroup,QuantityOfStudents,FacilityId")] StudentsGroup studentsGroup)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (ModelState.IsValid)
            {
                _context.Add(studentsGroup);
                await _context.SaveChangesAsync();
                cache.SetStudentsGroups();

                return RedirectToAction(nameof(Index));
            }
            ViewData["FacilityId"] = new SelectList(_context.Facilities, "FacilityId", "FacilityName", studentsGroup.FacilityId);
            return View(studentsGroup);
        }

        // GET: StudentsGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (id == null || _context.StudentsGroups == null)
            {
                return NotFound();
            }

            var studentsGroup = cache.GetStudentsGroups()
                .FirstOrDefault(m => m.StudentsGroupId == id); if (studentsGroup == null)
            {
                return NotFound();
            }
            ViewData["FacilityId"] = new SelectList(_context.Facilities, "FacilityId", "FacilityName", studentsGroup.FacilityId);
            return View(studentsGroup);
        }

        // POST: StudentsGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentsGroupId,NumberOfGroup,QuantityOfStudents,FacilityId")] StudentsGroup studentsGroup)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (id != studentsGroup.StudentsGroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentsGroup);
                    await _context.SaveChangesAsync();
                    cache.SetStudentsGroups();
                    var casheL = HttpContext.RequestServices.GetService<LessonService>();
                    casheL.SetLessons();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentsGroupExists(studentsGroup.StudentsGroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacilityId"] = new SelectList(_context.Facilities, "FacilityId", "FacilityName", studentsGroup.FacilityId);
            return View(studentsGroup);
        }

        // GET: StudentsGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (id == null || _context.StudentsGroups == null)
            {
                return NotFound();
            }

            var studentsGroup = cache.GetStudentsGroups()
                .FirstOrDefault(m => m.StudentsGroupId == id);
            if (studentsGroup == null)
            {
                return NotFound();
            }

            return View(studentsGroup);
        }

        // POST: StudentsGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetService<StudentsGroupService>();

            if (_context.StudentsGroups == null)
            {
                return Problem("Entity set 'LessonsDbContext.StudentsGroups'  is null.");
            }
            var studentsGroup = cache.GetStudentsGroups()
                .FirstOrDefault(m => m.StudentsGroupId == id);
            if (studentsGroup != null)
            {
                _context.Lessons.RemoveRange(studentsGroup.Lessons);
                _context.StudentsGroups.Remove(studentsGroup);
                

            }

            await _context.SaveChangesAsync();
            cache.SetStudentsGroups();
            var casheL = HttpContext.RequestServices.GetService<LessonService>();
            casheL.SetLessons();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentsGroupExists(int id)
        {
          return (_context.StudentsGroups?.Any(e => e.StudentsGroupId == id)).GetValueOrDefault();
        }
        private IEnumerable<StudentsGroup> Sort_Search(IEnumerable<StudentsGroup> studentsGroups, SortState sortOrder, string searchFacility, string searchStudentGroup)
        {
            switch (sortOrder)
            {
                case SortState.StudentGroupAsc:
                    studentsGroups = studentsGroups.OrderBy(s => s.NumberOfGroup);
                    break;
                case SortState.StudentGroupDesc:
                    studentsGroups = studentsGroups.OrderByDescending(s => s.NumberOfGroup);
                    break;
                case SortState.FacilityNameAsc:
                    studentsGroups = studentsGroups.OrderBy(s => s.Facility.FacilityName);
                    break;
                case SortState.FacilityNameDesc:
                    studentsGroups = studentsGroups.OrderByDescending(s => s.Facility.FacilityName);
                    break;
            }
            studentsGroups = studentsGroups
           .Where(o => o.Facility.FacilityName.Contains(searchFacility ?? "") 
           & (o.NumberOfGroup.Contains(searchStudentGroup ?? "")));

            return studentsGroups;
        }
    }
}

Study/Views/StudentsGroups/Create.cshtml
@model StudentsGroup

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить</h1>

<h4>Группа студентов</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumberOfGroup" class="control-label"></label>
                <input asp-for="NumberOfGroup" class="form-control" />
                <span asp-validation-for="NumberOfGroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityOfStudents" class="control-label"></label>
                <input asp-for="QuantityOfStudents" class="form-control" />
                <span asp-validation-for="QuantityOfStudents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacilityId" class="control-label"></label>
                <select asp-for="FacilityId" class ="form-control" asp-items="ViewBag.FacilityId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Study/Views/StudentsGroups/Delete.cshtml
@model StudentsGroup

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удалить</h1>

<h3>Вы уроверены что хотите этого</h3>
<div>
    <h4>StudentsGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfGroup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityOfStudents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityOfStudents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Facility.FacilityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Facility.FacilityName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentsGroupId" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Study/Views/StudentsGroups/Details.cshtml
@model StudentsGroup

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Детали</h1>

<div>
    <h4>Группа студентов</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfGroup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityOfStudents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityOfStudents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Facility.FacilityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Facility.FacilityName)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("admin")){
        <a class="link-warning" asp-action="Edit" asp-route-id="@Model?.StudentsGroupId">Обновить</a>
    }
    <a asp-action="Index">Вернуться к списку</a>
</div>

Study/Views/StudentsGroups/Edit.cshtml
@model StudentsGroup

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Обновить</h1>

<h4>Группа студентов</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentsGroupId" />
            <div class="form-group">
                <label asp-for="NumberOfGroup" class="control-label"></label>
                <input asp-for="NumberOfGroup" class="form-control" />
                <span asp-validation-for="NumberOfGroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityOfStudents" class="control-label"></label>
                <input asp-for="QuantityOfStudents" class="form-control" />
                <span asp-validation-for="QuantityOfStudents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacilityId" class="control-label"></label>
                <select asp-for="FacilityId" class="form-control" asp-items="ViewBag.FacilityId"></select>
                <span asp-validation-for="FacilityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-outline-warning" type="submit" value="Save"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Study/Views/StudentsGroups/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model StudentsGroupViewModel

@{
    ViewData["Title"] = "Группы студентов";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string NumberOfGroup = Model.NumberOfGroup;
    string Facility = Model.Facility;
}

<h1>Группы студентов</h1>
    @if (User.IsInRole("admin"))
    {
        <p>

            <a class="link-success" asp-action="Create">Добавить</a>

        </p>
    }
<form  action="@Url.Action("Index", "StudentsGroups")" method="post">
    <div class="row g-3">
        <div class="col-auto">
            @Html.TextBox("NumberOfGroup", NumberOfGroup, new {placeholder="Номер группы", style = "width: 100px;",@class="form-control custom-font-size"})
        </div>
        <div class="col-auto">
            @Html.TextBox("Facility", Facility, new {placeholder="Факультет", style = "width: 100px;",@class="form-control custom-font-size"})
        </div>
        <div class="col-auto">
            <input class="btn btn-outline-primary" style="margin-left: 10px" type="submit" value="Найти" />
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.SortViewModel.StudentGroupState>
                    @Html.DisplayNameFor(model => model.NumberOfGroup)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentsGroups.FirstOrDefault().QuantityOfStudents)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.SortViewModel.FacilityNameState>
                    @Html.DisplayNameFor(model => model.Facility)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.StudentsGroups) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfGroup)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityOfStudents)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Facility.FacilityName)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    <a class="link-warning" asp-action="Edit" asp-route-id="@item.StudentsGroupId">Обновить</a> |
                    <a class="link-info" asp-action="Details" asp-route-id="@item.StudentsGroupId">Детали</a> |
                    <a class="link-danger" asp-action="Delete" asp-route-id="@item.StudentsGroupId">Удалить</a>
                </td>
            }
            else
            {
                <td>
                    <a class="link-info" asp-action="Details" asp-route-id="@item.StudentsGroupId">Детали</a> |
                </td>
            }
        </tr>
}
    </tbody>
</table>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>